'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Deploy_Office.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Configuration&gt;
        '''  &lt;Add OfficeClientEdition=&quot;64&quot; Channel=&quot;{CHANNEL}&quot; AllowCdnFallback=&quot;True&quot; OfficeMgmtCOM=&quot;False&quot;&gt;
        '''    &lt;Product ID=&quot;{PRODUCTID}&quot;&gt;
        '''      &lt;Language ID=&quot;MatchOS&quot; Fallback=&quot;en-us&quot; /&gt;
        '''    &lt;/Product&gt;
        '''  &lt;/Add&gt;
        '''  &lt;Display AcceptEULA=&quot;True&quot; /&gt;
        '''  &lt;Property Name=&quot;PinIconsToTaskbar&quot; Value=&quot;False&quot; /&gt;
        '''  &lt;Property Name=&quot;FORCEAPPSHUTDOWN&quot; Value=&quot;True&quot; /&gt;
        '''  &lt;Property Name=&quot;AUTOACTIVATE&quot; Value=&quot;False&quot; /&gt;
        '''&lt;/Configuration&gt;.
        '''</summary>
        Friend ReadOnly Property configuration_xml() As String
            Get
                Return ResourceManager.GetString("configuration.xml", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
